Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BlogDiscussion2.Data;
using BlogDiscussion2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BlogDiscussion2.ViewModels;

namespace BlogDiscussion2.Controllers
{
    public class BlogsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public BlogsController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Blogs
        public async Task<IActionResult> Index()
        {
            return View(await _context.blogs.ToListAsync());
        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> LikeBlog(Int32 id)
        {
            Blog blog = _context.blogs.Find(id);
            blog.likes++; // Increase like count
            _context.Update(blog);
            await _context.SaveChangesAsync();
            User user = await GetCurruntUserAsync();
            Notification noti = new Notification
            {
                user = user,
                label = "Like",
                body = user.UserName + " Liked Your Blog: " + blog.title
            };
            await _context.notifications.AddAsync(noti);
            await _context.SaveChangesAsync();
            return Json(blog);
        }
        // GET: Blogs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.blogs
                .FirstOrDefaultAsync(m => m.id == id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }
        public async Task<IActionResult> ViewBlog(Int32? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            Blog blog = await _context.blogs
                .Include(blog => blog.users)
                .FirstOrDefaultAsync(blog => blog.id == id);
            if(blog == null)
            {
                return NotFound();
            }
            BlogViewModel blogViewModel = new BlogViewModel
            {
                id = blog.id,
                title = blog.title,
                body = blog.body,
                category = blog.category,
                createdOn = blog.createdOn,
                likes = blog.likes,
                users = blog.users
            };
            return View(blogViewModel);
        }
        // GET: Blogs/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,title,body,category,likes,createdOn,isPublished")] Blog blog)
        {
            if (ModelState.IsValid)
            {
                blog.users = await GetCurruntUserAsync();
                blog.isPublished = true;
                _context.Add(blog);
                Console.WriteLine(blog.users.Id);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.blogs.FindAsync(id);
            if (blog == null)
            {
                return NotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,title,body,category,likes,createdOn,isPublished")] Blog blog)
        {
            if (id != blog.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(blog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BlogExists(blog.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(blog);
        }

        // GET: Blogs/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var blog = await _context.blogs
                .FirstOrDefaultAsync(m => m.id == id);
            if (blog == null)
            {
                return NotFound();
            }

            return View(blog);
        }

        // POST: Blogs/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var blog = await _context.blogs.FindAsync(id);
            _context.blogs.Remove(blog);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BlogExists(int id)
        {
            return _context.blogs.Any(e => e.id == id);
        }

        private Task<User> GetCurruntUserAsync() => _userManager.GetUserAsync(HttpContext.User);
    }
}

Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlogDiscussion2</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
    @{
        foreach (var cookie in HttpContextAccessor.HttpContext.Request.Cookies)
        {
            if (@cookie.Key == "Theme" && @cookie.Value == "DARK")
            {
                <link rel="stylesheet" href="~/css/app-dark.css" />
                break;
            }
            else if (@cookie.Key == "Theme" && @cookie.Value == "LIGHT")
            {
                <link rel="stylesheet" href="~/css/app-light.css" />
                break;
            }
        }
    }
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <script src="~/lib/font-awesome/js/all.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlogDiscussion</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Blogs" asp-action="Create">Write Blog</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BlogDiscussion2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            @*<p>@ViewData["theme"]</p>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/tinymce/tinymce.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>